name: Feature Issue
description: 기본 Feature 이슈를 만들 때 사용하는 템플릿입니다.
title: "Feature"
body:
  - type: input
    id: general_outline
    attributes:
      label: 개요
      description: 해당 이슈에 대한 전체적인 내용을 적습니다.
    validations:
      required: true
  - type: textarea
    id: contents
    attributes:
      label: 작업 할 내용
      description: 해당 이슈에 대해서 작업해야할 내용들을 적어주세요.
      placeholder: 작업 할 내용들을 적어주세요.
    validations:
      required: true
  - type: textarea
    id: etc
    attributes:
      label: 기타 사항
      description: 추가로 적을 내용들을 적어주세요.
      placeholder: 기타
    validations:
      required: false
